version: "3"

services:
  consumer:
    build: .
    container_name: consumer
    restart: "always"
    networks:
      - mynetwork
    volumes:
      - app:/consumer/app

networks:
  mynetwork:
    external: true

volumes:
  app:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\Users\eloua\OneDrive\Desktop\IMT Atlantique\FISE A3 DASCI\architecture big data\projet\ARCHIBIGD-B\consumer\app'

